### ISSUE TITLE
能支持aliplayer的key提取嘛

### ISSUE THREAD

**Issue by LiuJiLan** [chuccp/chrome_extensions#2]
网站是极客时间的训练营, 用的是aliplayer的解决方案。
如有需要可以提供账号测试。
https://u.geekbang.org/

**Comment by chuccp** [comment]
极客时间 貌似没有做加密？m3u8可以直接通过调试直接获取？？

**Comment by LiuJiLan** [comment]
是的, 我已经解决了。他们给ts加了密, 二次解谜就解决了

**Comment by chuccp** [comment]
密钥解密简单吗？我没会员看不到会员的m3u8链接，可否发一个来看下？

**Comment by LiuJiLan** [comment]
key的获取是在https://blog.weimo.info/archives/440/里面提到的断点的那个for循环里面加console.log(btoa(String.fromCharCode.apply(null, new Uint8Array(i._sce_dlgtqredxx))));

**Comment by chuccp** [comment]
我破解保利威方法和这个类似，不过是有插件在，就不用打断点，直接复制就可以
