### ISSUE TITLE
Invalid value for 'web_accessible_resources[0]'.无法加载清单

### ISSUE THREAD

**Issue by bugushe** [chuccp/chrome_extensions#4]
Invalid value for 'web_accessible_resources[0]'.无法加载清单

**Comment by chuccp** [comment]
请问下，访问的是哪一个网站？？

**Comment by chuccp** [comment]
请问下，是哪一个浏览器？

**Comment by chuccp** [comment]
请问下，是哪一个浏览器，版本是多少？

**Comment by bugushe** [comment]
百分浏览器> 请问下，是哪一个浏览器，版本是多少？

**Comment by bugushe** [comment]
> 请问下，是哪一个浏览器，版本是多少？

最后发布的那版

**Comment by chuccp** [comment]
Manifest V3 从 Chrome [88](https://chromiumdash.appspot.com/schedule)开始提供，百分浏览器内核是86版的，太老了，建议换一个浏览器

**Comment by bugushe** [comment]
> Manifest V3 从 Chrome [88](https://chromiumdash.appspot.com/schedule)开始提供，百分浏览器内核是86版的，太老了，只支持Manifest V2，建议换一个浏览器

好的，谢谢

**Comment by chuccp** [comment]
你要破解的是哪一个网站？

**Comment by bugushe** [comment]
> 你要破解的是哪一个网站？

我其实不需要用，有自己写的Python脚本，无意看见了你写的好的插件，就想收藏一下，几乎也没下过啥保利威视频。

**Comment by chuccp** [comment]
哈哈，也是高手哦，我这目的是为了给普通人用着方便写的
