### ISSUE TITLE
https://www.shenlanxueyuan.com/  网站的m3u8视频怎么下载？

### ISSUE THREAD

**Issue by lper** [chuccp/chrome_extensions#5]
www.shenlanxueyuan.com  能支持一下吗？

**Comment by chuccp** [comment]
不用了，我看到加密源了

**Comment by chuccp** [comment]
> [www.shenlanxueyuan.com](http://www.shenlanxueyuan.com) 能支持一下吗？

已经支持了，麻烦试一试

**Comment by lper** [comment]
感谢~，可以用了
